services:

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: station_meteo_backend:1.2
    container_name: "station_meteo_backend_echo"
    restart: unless-stopped
    env_file: backend/.env
    ports:
      - "5001:5001"
    environment:
      - PORT=${SERVER_PORT}
      - MONGO_DB_URL="mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@${MONGO_DB_HOST}:${MONGO_DB_PORT}/${MONGO_DB_NAME}?authSource=admin"
    depends_on:
      - mongo
    networks:
      - backend
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro


  mongo:
    image: mongo
    container_name: "station_meteo_mongo"
    restart: always
    env_file: .env
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongodb/initdb.d/initdb.js:/docker-entrypoint-initdb.d/initdb.js:ro
      - mongodb-data:/data/db/
    networks:
      - backend

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - backend
    env_file: .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongodb-data:

networks:
  backend:
